### ISSUE TITLE
展示のタイムテーブルへのご相談

### ISSUE THREAD

**Issue by JunichiWatanuki** [ntt-developers/ntt-tech-conference-01#1]
E2D3デモ展示を予定している綿貫です。  
展示のタイムテーブルに書いておきたい内容（項目）としては。下記４つがあります。  

### 1. デモ体験に必要な資材
  * ExcelOnline または Excel2013以降を使えるPC
  * インターネット接続環境

### 2. 利用チュートリアル
http://e2d3.org/ja/app-install/

### 3. 利用者向けのFAQ
http://e2d3.org/ja/faq/

### 4. 可視化テンプレート開発者向けマニュアル
https://github.com/e2d3/e2d3/wiki/Getting-Started_ja

他の展示内容と、項目が共通するものがありましたら、追加いただけますとありがたいです。

---

またgh-pagesへの反映方法などは、いきなりプルリクする前に、内容を確認いただいてからと思っております.
よろしくお願いします。

**Comment by ykubota** [comment]
LGTM, please send PR :)

**Comment by ykubota** [comment]
Fixed by #41
