### ISSUE TITLE
ntt-developers.github.ioが404

### ISSUE THREAD

**Issue by AkihiroSuda** [ntt-developers/ntt-tech-conference-01#25]
https://ntt-developers.github.io にも何かしらのページがあると良いかと思うのですがいかがでしょうか? (/ntt-tech-conference-01 にredirectするだけの内容でいいと思います)

**Comment by hisaharu** [comment]
とりあえず @AkihiroSuda さんを ntt-developers repo にinviteしました。

**Comment by AkihiroSuda** [comment]
ありがとうございます

**Comment by hisaharu** [comment]
置きました
https://ntt-developers.github.io/
