### ISSUE TITLE
CI/CD化

### ISSUE THREAD

**Issue by hisaharu** [ntt-developers/ntt-tech-conference-01#5]
* git上では `.slim` だけを版管理
* CI通ったらマージ
* CDでHTMLをgh-pagesにデプロイ
っていうリファクタリングしたい

#31 でまだ未解決のTODO
- [x] CD元ブランチを `gh-pages` から `master` に変える
- [x] `master` ブランチから `.html` と `asset/` を ignore
- [x] CIのdiffを止める
- [x] Deploy先ブランチを `gh-pages` に変える

**Comment by kumagi** [comment]
https://github.com/ntt-developers/ntt-tech-conference-01/pull/33
で全部できたつもりなのでおねがいします。

**Comment by hisaharu** [comment]
done!
