### ISSUE TITLE
After Partyの案内を追加する

### ISSUE THREAD

**Issue by Mahito** [ntt-developers/ntt-tech-conference-01#52]
## 背景
* After Partyの案内がない（震え声）

## ゴール
* index.slim あたりにAfter Partyの案内とconnpassのURLを記載する

**Comment by hisaharu** [comment]
#51 でマージ済みだがdeployがコケてる

**Comment by Mahito** [comment]
なるほど

**Comment by Mahito** [comment]
対応確認できたのでclose
