### ISSUE TITLE
モバイルでの表示が一部だけ崩れている

### ISSUE THREAD

**Issue by manji-0** [ntt-developers/ntt-tech-conference-01#61]
## 事象
iPhone(6S, Safari)でページを閲覧した際、「参加登録」の章だけ文章が3カラム表示になっている

![3](https://cloud.githubusercontent.com/assets/7368277/21952494/c63e0d2e-da61-11e6-903f-e7d534679ca6.jpg)

## 問題
読みにくい

## 修正方針
他の章と同じく、1カラム表示に修正する

## 修正方法
自分には知識が無い

**Comment by kumagi** [comment]
iPhone5sのSafari, Chromeでも再現を確認。

**Comment by sudoyu** [comment]
Xperia Z1のChromeでも再現角煮。
縦表示で2カラム、横表示で3カラム。

**Comment by kumagi** [comment]
#66 で直った。

**Comment by kumagi** [comment]
![preview](https://i.gyazo.com/4d9b8045408160138624efb4a43fa75e.png)

**Comment by kumagi** [comment]
直ってなかったらreopenしてくれ。
